# Generated by Django 3.0.4 on 2020-05-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='Author',
            new_name='author',
        ),
    ]
